Add support of eslint-plugin-putout
codacy/codacy-eslint pull request #779
Opened 2020-09-28 16:12 UTC by coderaiser

Added support of `eslint plugin` for code transformer [putout](https://github.com/coderaiser/putout) that fixes everything it can find according to best practices. It works mostly with code, not with formatting, so this is a great addition to `eslint` :). 

Right now linting of `putout` project is failing on `codacy`, because it doesn't support `eslint-plugin-putout`, but `putout` checks itself on every commit, has `100%` coverage, here is examples of checks:
- [github actions](https://github.com/coderaiser/putout/runs/1177535616)
- [sonarqube](https://github.com/coderaiser/putout/runs/1177539846)
- [travis](https://github.com/coderaiser/putout/runs/1177535494)

Would be amazing to add `codacy` to list of checkers :).

2020-09-29 09:00 UTC, lolgab requested changes

2020-09-29 09:00 UTC, lolgab commented on src/docGeneratorMain.ts
> +      `${githubBaseUrl}/coderaiser/putout/master/packages/eslint-plugin-putout/lib/${pattern}/${pattern}.md`,
I checked the putout repository and the md files seems to me all called `README.md`:
```suggestion
      `${githubBaseUrl}/coderaiser/putout/master/packages/eslint-plugin-putout/lib/${pattern}/README.md`,
```

2020-09-29 10:20 UTC, coderaiser commented on src/docGeneratorMain.ts
> +      `${githubBaseUrl}/coderaiser/putout/master/packages/eslint-plugin-putout/lib/${pattern}/${pattern}.md`,
@lolgab yes, you right, thank you

2020-09-29 14:17 UTC, lolgab commented
Thank you for your contribution @coderaiser, it's really appreciated!
I added a commit so we can have a green CI while maintaining our internal conventions.
However, we have an internal framework to evaluate a decide if we want to add new plugins to Codacy tools.
So we'll take some time to evaluate the plugin if we can add it to Codacy.

2023-07-03 14:58 UTC, codacy-vrhpires commented
It was recently added.

2023-07-03 14:58 UTC, closed without merging